version: "3"

services:
  node:
    image: zrxmoto/axnetlabs-node-red:latest  
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.node.rule=Host(`pjfarmspineriver.com`)"
      - "traefik.http.routers.node.entrypoints=nodesecure"
      - "traefik.http.routers.node.tls.certresolver=myresolver"
    depends_on:
      - mongodb
      - influxdb
    #ports:
    #  - "1880:1880"
    networks:
      - pjfarms-net
  mongodb:
    image: mongo
    restart: always
    volumes:
      - axnet-iot-data-mongo:/data/db
    networks:
      - pjfarms-net
  influxdb:
    image: influxdb
    restart: always
    volumes:
      - axnet-iot-data-influx:/var/lib/influxdb2
    networks:
      - pjfarms-net
  web:
    image: zrxmoto/axnetlabs-pj-web:latest
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`pjfarmspineriver.com`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=myresolver"
    #ports:
    #  - "80:80"
    networks:
      - pjfarms-net

  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.nodesecure.address=:1880"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=joeaxberg@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "1880:1880"
    networks:
      - pjfarms-net
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

networks:
  pjfarms-net:

volumes:
  axnet-iot-data-mongo:
  axnet-iot-data-influx: