version: "3"

services:
  node-red:
    image: zrxmoto/axnetlabs-node-red:latest  
    restart: always
    ports:
      - "1880:1880"
    networks:
      - axnet-iot-net
  mongodb:
    image: mongo
    restart: always
    volumes:
      - axnet-iot-data-mongo:/data/db
    networks:
      - axnet-iot-net

networks:
  axnet-iot-net:

volumes:
  axnet-iot-data-mongo: