version: "3"

services:
  node-red:
    image: zrxmoto/axnetlabs-node-red:latest  
    restart: always
    depends_on:
      - mongodb
      - influxdb
    ports:
      - "1880:1880"
    networks:
      - axnet-iot-net
  mongodb:
    image: mongo
    restart: always
    volumes:
      - axnet-iot-data-mongo:/data/db
    networks:
      - axnet-iot-net
  influxdb:
    image: influxdb
    restart: always
    volumes:
      - axnet-iot-data-influx:/var/lib/influxdb2
    networks:
      - axnet-iot-net
  web:
    image: zrxmoto/axnetlabs-pj-web:latest
    restart: always

networks:
  axnet-iot-net:

volumes:
  axnet-iot-data-mongo:
  axnet-iot-data-influx: